In [ ]:
import numpy as np
from scipy.io import loadmat

In [ ]:
datadict = loadmat('results.mat')
args = np.argmax(datadict['All_val_accuracy'], axis = 1)

In [ ]:
print('loss')
values = datadict['All_loss'][np.arange(60), args]
average = np.average(values)
standard_deviation = (1/59 * np.sum((values-average)**2))**0.5
print('Average = ', average)
print('Standard deviation = ', standard_deviation)

loss
Average =  0.12230754556755224
Standard deviation =  0.02908671094263097


In [ ]:
print('accuracy')
values = datadict['All_accuracy'][np.arange(60), args]
average = np.average(values)
standard_deviation = (1/59 * np.sum((values-average)**2))**0.5
print('Average = ', average)
print('Standard deviation = ', standard_deviation)

accuracy
Average =  0.9555555502573649
Standard deviation =  0.01123023546752626


In [ ]:
print('val_loss')
values = datadict['All_val_loss'][np.arange(60), args]
average = np.average(values)
standard_deviation = (1/59 * np.sum((values-average)**2))**0.5
print('Average = ', average)
print('Standard deviation = ', standard_deviation)

val_loss
Average =  0.10888362464805444
Standard deviation =  0.02823926142993674


In [ ]:
print('val_accuracy')
values = datadict['All_val_accuracy'][np.arange(60), args]
average = np.average(values)
standard_deviation = (1/59 * np.sum((values-average)**2))**0.5
print('Average = ', average)
print('Standard deviation = ', standard_deviation)

val_accuracy
Average =  0.9677545706431071
Standard deviation =  0.009600228624129395


In [ ]:
print('test_loss')
values = datadict['All_results'][:, 0]
average = np.average(values)
standard_deviation = (1/59 * np.sum((values-average)**2))**0.5
print('Average = ', average)
print('Standard deviation = ', standard_deviation)

test_loss
Average =  0.11066975171367327
Standard deviation =  0.016964106683444433


In [ ]:
print('test_accuracy')
values = datadict['All_results'][:, 1]
average = np.average(values)
standard_deviation = (1/59 * np.sum((values-average)**2))**0.5
print('Average = ', average)
print('Standard deviation = ', standard_deviation)

test_accuracy
Average =  0.9631637215614319
Standard deviation =  0.007123395329516565


In [ ]:
print('confusion_matrix')
values = datadict['All_confusion']
average = np.average(values, axis=0)
standard_deviation = (1/59*np.sum((values - np.tile(average, (60, 1, 1)))**2, axis = 0))**0.5

average = average[:, [1, 2, 0]]; average = average[[1, 2, 0], :]
standard_deviation = standard_deviation[:, [1, 2, 0]]; standard_deviation = standard_deviation[[1, 2, 0], :]

print('Average = \n', average)
print('Standard deviation = \n', standard_deviation)

confusion_matrix
Average = 
 [[156.9          0.71666667   3.38333333]
 [  2.38333333 149.28333333   3.33333333]
 [  4.06666667   2.76666667 129.16666667]]
Standard deviation = 
 [[2.04773542 0.88474197 2.13994825]
 [1.34153551 3.34507818 2.74736648]
 [2.17743954 1.4885628  2.7810903 ]]
